In [1]:
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [2]:
import pandas as pd
import numpy as np


In [3]:
digits = load_digits()

In [4]:
type(digits)

sklearn.utils.Bunch

In [5]:
print(digits.data.shape)

(1797, 64)


In [6]:
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

### Logistic Regression

In [7]:
lr = LogisticRegression(solver='lbfgs',max_iter=10000)
lr.fit(X_train, y_train)

LogisticRegression(max_iter=10000)

In [8]:
lr.score(X_test, y_test)

0.9740740740740741

### Support Vector Classification (SVC)

In [9]:
svm = SVC()
svm.fit(X_train,y_train)

SVC()

In [10]:
svm.score(X_test, y_test)

0.987037037037037

### Random Forest

In [11]:
rf = RandomForestClassifier(n_estimators=100)

In [12]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [13]:
rf.score(X_test,y_test)

0.9777777777777777

### KFold

In [14]:
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

In [15]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [16]:
sfold = StratifiedKFold(n_splits=3)

In [17]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [18]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [19]:
score_log = []
score_rf = []
score_svc = []

In [20]:
for train_index, test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                        digits.target[train_index], digits.target[test_index]
    
    score_log.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=50), X_train, X_test, y_train, y_test))
    score_svc.append(get_score(SVC(), X_train, X_test, y_train, y_test))

In [21]:
score_log

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [22]:
score_rf

[0.9365609348914858, 0.9465776293823038, 0.9165275459098498]

In [23]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [24]:
from sklearn.model_selection import cross_val_score

In [25]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

array([0.925     , 0.875     , 0.93871866, 0.93314763, 0.89693593])

In [26]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.93055556, 0.90555556, 0.96100279, 0.95821727, 0.91643454])

In [27]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])